Inicio del manejo de errores

diff --git a/udebs/addons/backharddi-ng-udeb/source/fin.d/backharddi b/udebs/addons/backharddi-ng-udeb/source/fin.d/backharddi
--- a/udebs/addons/backharddi-ng-udeb/source/fin.d/backharddi
+++ b/udebs/addons/backharddi-ng-udeb/source/fin.d/backharddi
@@ -7,13 +7,7 @@ PARTIMAGE_STATS=/var/log/partimage/partimage.stats
 NTFSCLONE_STATS=/var/log/ntfsclone.stats
 PARTCLONE_STATS=/var/log/partclone.stats
 DD_STATS=/var/log/dd.stats
-STOP_MONITOR=/tmp/stop_monitor
-ERROR=/tmp/backharddi_error
 CDNUM=/tmp/cdnum
-
-error(){
-	touch $STOP_MONITOR $ERROR
-}
 
 parse_stats(){
 	if [ -f $imagenes/$id/ntfsclone ]; then
@@ -118,30 +112,30 @@ monitor(){
 comprime(){
 	if [ -f $id/compresion ]; then 
 		case "$(cat $id/compresion)" in
-			lzo) lzop -1 -c - ;;
-			lzma) lzma -z -c ;;
-			*) cat ;;
+			lzo) lzop -1 -c - || error 31;;
+			lzma) lzma -z -c || error 32;;
+			*) cat || error 33;;
 		esac	
 	else
-		cat 
+		cat || error 33
 	fi
 }
 
 descomprime(){
 	if [ -f $imagenes/$id/compresion ]; then 
 		case "$(cat $imagenes/$id/compresion)" in
-			lzo) lzop -d -c - ;;
-			lzma) lzma -d -c ;;
-			gzip) zcat ;;
+			lzo) lzop -d -c - || error 34;;
+			lzma) lzma -d -c || error 35;;
+			*) cat error 36;;
 		esac	
 	else
-		cat
+		cat || error 36
 	fi
 }
 
 concatena2(){
 	for i in $imagenes/$id/img.*; do
-		cat $i || exit 1
+		cat $i || error 41
 	done
 }
 
@@ -151,11 +145,11 @@ concatena(){
 			db_get backharddi/net/port
 			port="$RET"
 			if [ -n "$port" ]; then
-				monitor | udp-receiver --nokbd --stat-period 2000 --portbase "$port" 2>>/var/log/udp-receiver
+				monitor | udp-receiver --nokbd --stat-period 2000 --portbase "$port" 2>>/var/log/udp-receiver || error 51
 				wait
 			else
-				port="$(wget -q -O - http://$server:$service_port/get?backup=$(echo $imagenes/$id | escape_string))"
-				monitor | udp-receiver --stat-period 2000 --portbase "$port" <&$OLD_STDIN 2>>/var/log/udp-receiver
+				port="$(wget -q -O - http://$server:$service_port/get?backup=$(echo $imagenes/$id | escape_string))" || error 52
+				monitor | udp-receiver --stat-period 2000 --portbase "$port" <&$OLD_STDIN 2>>/var/log/udp-receiver || error 51
 				wait
 			fi
 		;;
@@ -195,33 +189,33 @@ concatena(){
 
 gen_cmd(){
 	if [ -f $id/ntfsclone ]; then
-		ntfsclone -s -o - $(cat $id/path) 2>$NTFSCLONE_STATS || error
+		ntfsclone -s -o - $(cat $id/path) 2>$NTFSCLONE_STATS || error 21
 	elif [ -f $id/partclone ]; then
-		partclone.ext4 -C -c -s $(cat $id/path) 2>$PARTCLONE_STATS || error
+		partclone.ext4 -C -c -s $(cat $id/path) 2>$PARTCLONE_STATS || error 22
 	elif [ -f $id/dd ]; then
 		map=${id#*/}
 		start=${map%-*}
 		end=${map#*-}
 		size=$((end-start+1))
-		dd_rescue $(cat $id/path) - -m $size 2>$DD_STATS && touch $STOP_MONITOR || error
+		dd_rescue $(cat $id/path) - -m $size 2>$DD_STATS && touch $STOP_MONITOR || error 23
 	else
-		partimage -B gui=no -M -V0 -dc -z0 -f3 save $(cat $id/path) stdout 2>$PARTIMAGE_STATS || error
+		partimage -B gui=no -M -V0 -dc -z0 -f3 save $(cat $id/path) stdout 2>$PARTIMAGE_STATS || error 24
 	fi
 }
 
 rest_cmd(){
 	if [ -f $imagenes/$id/ntfsclone ]; then
-		ntfsclone -r -O $(cat $id/path) - 2>$NTFSCLONE_STATS >&2 || error
+		ntfsclone -r -O $(cat $id/path) - 2>$NTFSCLONE_STATS >&2 || error 25
 	elif [ -f $imagenes/$id/partclone ]; then
-		partclone.ext4 -r -s - -o $(cat $id/path) 2>$PARTCLONE_STATS || error
+		partclone.ext4 -r -s - -o $(cat $id/path) 2>$PARTCLONE_STATS || error 26
 	elif [ -f $imagenes/$id/dd ]; then
 		map=${id#*/}
 		start=${map%-*}
 		end=${map#*-}
 		size=$((end-start+1))
-		dd_rescue - $(cat $id/path) -m $size 2>$DD_STATS && touch $STOP_MONITOR || error
+		dd_rescue - $(cat $id/path) -m $size 2>$DD_STATS && touch $STOP_MONITOR || error 27
 	else
-		partimage -B gui=no -f3 restore $(cat $id/path) stdin 2>$PARTIMAGE_STATS || error
+		partimage -B gui=no -f3 restore $(cat $id/path) stdin 2>$PARTIMAGE_STATS || error 28
 	fi
 }
 
@@ -294,7 +288,7 @@ for dev in *; do
 				*) 
 					case "$medio" in
 						net)
-							port="$(wget -q -O - http://$server:$service_port/put?file=$(echo $imagenes/$id/img | escape_string))"
+							port="$(wget -q -O - http://$server:$service_port/put?file=$(echo $imagenes/$id/img | escape_string))" || error 53
 							monitor | gen_cmd | comprime | nc $server $port
 							success_gen=true
 						;;
@@ -303,7 +297,7 @@ for dev in *; do
 						;;
 					esac				
 				   	wait
-				   	[ ! -f $ERROR ]
+				   	[ ! -f $ERROR ] || exit $(cat $ERROR)
 				;;
 			esac
 		elif [ -f $id/rest ]; then
@@ -320,7 +314,7 @@ for dev in *; do
 				;;
 				*) concatena | descomprime | rest_cmd 
 				   wait
-				   [ ! -f $ERROR ]
+				   [ ! -f $ERROR ] || exit $(cat $ERROR)
 				;;
 			esac
 		fi
@@ -328,6 +322,6 @@ for dev in *; do
 done
 
 if [ "$success_gen" = true ]; then
-	port="$(wget -q -O - http://$server:$service_port/putBackupMetadata)"
-	pack_backup_metadata $imagenes | nc $server $port
+	port="$(wget -q -O - http://$server:$service_port/putBackupMetadata)" || error 54
+	pack_backup_metadata $imagenes | nc $server $port || error 55
 fi
